notifications:
  email: false
language: ruby
addons:
  postgresql: '9.6'
env:
  - TRAVIS_NODE_VERSION="9"
cache:
  bundler: true
  directories:
    - vendor/bundle
    - node_modules
    - $HOME/.rvm/gems
install:
  - bundle install
  - nvm install 9
  - yarn install
before_script:
  - nvm use 9
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake db:seed
  - RAILS_ENV=test bundle exec rake
  - node lib/build.js
  - git diff --exit-code --quiet public/data.json

