default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: mdn_compat_data_explorer_development
test:
  <<: *default
  database: mdn_compat_data_explorer_test

production:
  <<: *default
  database: mdn_compat_data_explorer_production
